### ISSUE TITLE
Please provide multi-Select on the Installer Package Content list

### ISSUE THREAD

**Issue by ChrisPulman** [tenacious/Auto.Squirrel#4]
When creating a Auto Squirrel project it is easy to add files but can only remove them one by one.
Please provide multi Select on the Installer Package Content list and allow removal of the selected items.

**Comment by tenacious** [comment]
Hello Chris,
unfortunately i'm not going develop further Auto.Squirrel, since i'm not use anymore Squirrel.Windows.

But if you have a bit of experience with WPF , you should be able to add this feature yourself.
See this [stackoverflow page for more info ](http://stackoverflow.com/questions/459375/customizing-the-treeview-to-allow-multi-select)

**Comment by ChrisPulman** [comment]
Thanks, I will fork this and make the extra features.
